(** This ISA is designed around the uniform value representation that the RTL implements. A total
    of 256 registers are split into 224 general-purpose registers (GPRs) and 32 floating-point
    registers (FPRs). Thus, floats get special treatment in this ISA which contains specialized
    instructions to operate directly on unboxed machine floats. Makes math fast and snappy :D *)

type reg = Reg of int [@@unboxed] [@@immediate64]

type float_reg = Float_reg of int [@@unboxed] [@@immediate64]

type func_id = Func_id of int [@@unboxed] [@@immediate64]

type prim_id = Prim_id of int [@@unboxed] [@@immediate64]

type t =
  (* load, move and bridge integers and floats *)
  | Load_int_imm of reg * int  (** dst, imm *)
  | Load_float_imm of float_reg * float  (** dst, imm *)
  | Mov of reg * reg  (** dst, src *)
  | Mov_float of float_reg * float_reg  (** dst, src *)
  | Box_float of reg * float_reg  (** dst (GPR), src (FPR) *)
  | Unbox_float of float_reg * reg  (** dst (FPR), src (GPR) *)
  (* value casts between integers and floats with special cases for boxed floats *)
  | Cast_int_float of float_reg * reg  (** dst (FPR), src (GPR) *)
  | Cast_float_int of reg * float_reg  (** dst (GPR), src (FPR) *)
  | Cast_int_float_boxed of reg * reg  (** dst, src *)
  | Cast_float_boxed_int of reg * reg  (** dst, src *)
  (* integer arithmetic *)
  | Add_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Add_int_imm of reg * reg * int  (** dst, src, imm *)
  | Sub_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Mul_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Mul_int_imm of reg * reg * int  (** dst, src, imm *)
  | Div_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Mod_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Neg_int of reg * reg  (** dst, src *)
  (* unboxed float arithmetic *)
  | Add_float of float_reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Add_float_imm of float_reg * float_reg * float  (** dst, lhs, imm *)
  | Sub_float of float_reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Mul_float of float_reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Mul_float_imm of float_reg * float_reg * float  (** dst, lhs, imm *)
  | Div_float of float_reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Neg_float of float_reg * float_reg  (** dst, src *)
  (* integer comparison *)
  | Eq_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Eq_int_imm of reg * reg * int  (** dst, src, imm *)
  | Ne_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Ne_int_imm of reg * reg * int  (** dst, src, imm *)
  | Lt_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Lt_int_imm of reg * reg * int  (** dst, src, imm *)
  | Le_int of reg * reg * reg  (** dst, lhs, rhs *)
  (* unboxed float comparison *)
  | Eq_float of reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Ne_float of reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Lt_float of reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Le_float of reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Gt_float of reg * float_reg * float_reg  (** dst, lhs, rhs *)
  | Ge_float of reg * float_reg * float_reg  (** dst, lhs, rhs *)
  (* integer bitwise *)
  | And_int of reg * reg * reg  (** dst, lhs, rhs *)
  | And_int_imm of reg * reg * int  (** dst, lhs, imm *)
  | Or_int of reg * reg * reg  (** dst, lhs, rhs *)
  | Or_int_imm of reg * reg * int  (** dst, lhs, imm *)
  | Xor_int of reg * reg * reg  (** dst, lhs, rhs *)
  (* control flow *)
  | Jmp of int  (** offset *)
  | Jmp_table of reg * int  (** tag, table_size *)
  | Jmp_table_offset of int  (** offset *)
  | Jt of reg * int  (** cond, offset *)
  | Jf of reg * int  (** cond, offset *)
  (* call layout *)
  | Call of reg * func_id * reg * int  (** dst, callee, args_base, nargs *)
  | Call_closure of reg * reg * reg * int  (** dst, callee, args_base, nargs *)
  | Call_prim of reg * prim_id * reg * int  (** dst, callee, args_base, nargs *)
  | Call_prim_managed of reg * prim_id * reg * int
      (** dst, callee, args_base, nargs *)
  | Tail_call of func_id * reg * int  (** callee, args_base, nargs *)
  | Tail_call_closure of reg * reg * int  (** callee, args_base, nargs *)
  | Ret of reg  (** src *)
  (* allocation and object creation *)
  | Alloc of reg * int  (** dst, nfields *)
  | Alloc_closure of reg * func_id * int  (** dst, callee, nfields *)
  | Alloc_array of reg * reg  (** dst, nfields_reg *)
  (* object property and closure metadata *)
  | Load_tag of reg * reg  (** dst, src *)
  | Store_tag of reg * int  (** base, tag *)
  | Load_upvar of reg * reg * int  (** dst, closure, index *)
  | Store_upvar of reg * reg * int  (** closure, src, index *)
  | Length of reg * reg  (** dst, src *)
  (* uniform memory and array access *)
  | Load_byte of reg * reg * reg  (** dst, base, index *)
  | Store_byte of reg * reg * reg  (** base, src, index *)
  | Load_field_int of reg * reg * int  (** dst, base, index *)
  | Load_field_float of reg * reg * int  (** dst, base, index *)
  | Load_field_ptr of reg * reg * int  (** dst, base, index *)
  | Load_array_int of reg * reg * reg  (** dst, base, index *)
  | Load_array_float of reg * reg * reg  (** dst, base, index *)
  | Load_array_ptr of reg * reg * reg  (** dst, base, index *)
  | Store_field_int of reg * reg * int  (** base, src, index *)
  | Store_field_float of reg * reg * int  (** base, src, index *)
  | Store_field_ptr of reg * reg * int  (** base, src, index *)
  | Store_array_int of reg * reg * reg  (** base, src, index *)
  | Store_array_float of reg * reg * reg  (** base, src, index *)
  | Store_array_ptr of reg * reg * reg  (** base, src, index *)
  (* exceptional control flow and algebraic effects *)
  | Push_handler of int  (** handler_offset *)
  | Pop_handler
  | Perform of reg * reg  (** dst, effect_instance *)
  (* system operations *)
  | Nop
  | Halt
